### ISSUE TITLE
Examples panic on Ubuntu

### ISSUE THREAD

**Issue by oskargustafsson** [gfx-rs/wgpu-rs#140]
All examples panic with the same error:
```
RUST_BACKTRACE=full cargo run --example cube
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/examples/cube`
thread 'main' panicked at 'internal error: entered unreachable code', /home/oskar/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/b51053d/wgpu-native/src/device.rs:150:5
stack backtrace:
   0:     0x55d5b534ad44 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55d5b534ad44 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55d5b534ad44 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55d5b534ad44 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55d5b53718fc - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55d5b5347467 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55d5b534d8b5 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55d5b534d8b5 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55d5b534d8b5 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55d5b534d5a6 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55d5b534dfb5 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55d5b5339ca3 - std::panicking::begin_panic::h388fb4712cd8b371
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:407
  12:     0x55d5b4d4c2be - wgpu_adapter_request_device
                               at /home/oskar/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/b51053d/wgpu-native/src/device.rs:150
  13:     0x55d5b4b72cbe - wgpu::Adapter::request_device::h73edcd099787d207
                               at src/lib.rs:564
  14:     0x55d5b4917adb - cube::framework::run::hcc7ccdd3b3a7321d
                               at examples/cube/../framework.rs:105
  15:     0x55d5b48f9765 - cube::main::h3ed8822a0442a267
                               at examples/cube/main.rs:364
  16:     0x55d5b48ea770 - std::rt::lang_start::{{closure}}::h4c16b6915395d96c
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  17:     0x55d5b534d9e3 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  18:     0x55d5b534d9e3 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  19:     0x55d5b535618a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  20:     0x55d5b534e4ad - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  21:     0x55d5b534e4ad - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  22:     0x55d5b534e4ad - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  23:     0x55d5b48ea749 - std::rt::lang_start::h70086e28cfd76dbc
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  24:     0x55d5b48f979a - main
  25:     0x7fdfc370d09b - __libc_start_main
  26:     0x55d5b48b11aa - _start
  27:                0x0 - <unknown>
```

OS is Ubuntu 18.10 using nvidia-driver-418. Hardware:
```
H/W path         Device           Class          Description
============================================================
                                  system         MS-7681 (To be filled by O.E.M.)
/0                                bus            P67A-GD55 (MS-7681)
/0/0                              memory         64KiB BIOS
/0/4                              memory         256KiB L1 cache
/0/5                              memory         1MiB L2 cache
/0/6                              memory         6MiB L3 cache
/0/27                             memory         8GiB System Memory
/0/27/0                           memory         4GiB DIMM DDR3 Synchronous 1333 MHz (0,8 ns)
/0/27/1                           memory         DIMM Synchronous [empty]
/0/27/2                           memory         4GiB DIMM DDR3 Synchronous 1333 MHz (0,8 ns)
/0/27/3                           memory         DIMM Synchronous [empty]
/0/68                             processor      Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
/0/100                            bridge         2nd Generation Core Processor Family DRAM Controller
/0/100/1                          bridge         Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port
/0/100/1/0                        display        GP104 [GeForce GTX 1080]
/0/100/1/0.1                      multimedia     GP104 High Definition Audio Controller
/0/100/16                         communication  6 Series/C200 Series Chipset Family MEI Controller #1
/0/100/1a                         bus            6 Series/C200 Series Chipset Family USB Enhanced Host 
```

**Comment by kvark** [comment]
This was fixed in https://github.com/gfx-rs/wgpu/pull/408, we just haven't gotten the `wgpu` dependency up to date in here.

**Comment by oskargustafsson** [comment]
I tested with the latest commit
```
[dependencies.wgn]
package = "wgpu-native"
version = "0.4"
git = "https://github.com/gfx-rs/wgpu"
rev = "6a963892b5a51f0ba854ad91ac269a3b0bc29d9c"

[dependencies.wgc]
package = "wgpu-core"
version = "0.1"
git = "https://github.com/gfx-rs/wgpu"
rev = "6a963892b5a51f0ba854ad91ac269a3b0bc29d9c"
```
but still get the same error.

**Comment by kvark** [comment]
Does `vkcube` work (from vulkan-tools package)?

**Comment by kvark** [comment]
Also, could you please do `println!("{:?}", adapter_id)` after you get it?

**Comment by oskargustafsson** [comment]
Actually, after installing `vulkan-tools` (which installs `libvulkan1`), the `wgpu-rs` examples run just fine. I didn't know it was a dependency.

**Comment by kvark** [comment]
It's not supposed to be a dependency, at least not in Release (while in Debug we enable the validation layers by default, so we need the SDK). So this is still a bug.

**Comment by RandomInsano** [comment]
I'm hitting the same problem on macOS 10.13.6, though a different line:

```
thread 'main' panicked at 'internal error: entered unreachable code', /Users/me/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/009bde0/wgpu-native/src/device.rs:176:5
```

Version 0.4.0.

**Comment by kvark** [comment]
@RandomInsano could you try the `master` version instead of 0.4? Also, I'm not seeing this line in the latest published 0.4.2: https://github.com/gfx-rs/wgpu/blob/55aab54b4e16cc4f6c8969971e1ee1d620159f80/wgpu-native/src/device.rs#L176

Perhaps, you could try `cargo update -p wgpu-native`?

**Comment by RandomInsano** [comment]
Sure! Let's see...

```
Merryweather:wgpu-rs edwinamsler$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
MyMachine:wgpu-rs me$ git pull
Already up to date.
MyMachine:wgpu-rs me$ cargo update -p wgpu-native 
    Updating git repository `https://github.com/gfx-rs/wgpu`
    Updating crates.io index
    Updating git repository `https://github.com/kvark/peek-poke`
MyMachine:wgpu-rs me$ cargo run --example shadow
   Compiling wgpu v0.4.0 (/Users/me/Documents/Code/rust/other/wgpu-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 12.70s
     Running `target/debug/examples/shadow`
thread 'main' panicked at 'internal error: entered unreachable code', /Users/me/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/009bde0/wgpu-native/src/device.rs:176:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Doesn't seem to be happy. Where exactly can I get 0.4.2?

**Comment by kvark** [comment]
Oh sorry, `cargo update -p` doesn't help here. `wgpu-rs` depends on `wgpu` crates by github paths, so you'd need to change `Cargo.toml` to select the latest revision (or just the master branch) for the `wgpu-native` and `wgpu-core` dependencies...

**Comment by kvark** [comment]
I believe this is now resolved
