### ISSUE TITLE
Compute Shader Fails on Linux/Intel on Some Inputs but Not Others

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu-rs#253]
## Preface

This is gonna a be a doozy, bare with me here :)

In my application, I am trying to use a compute shader to perform an expensive and memory bandwidth heavy texture processing step. When given the right input file on affected gpus, the texture input to this compute shader will be completely blank.

These examples work on my Windows 10 system with a 1080ti. The failing example doesn't work on my Kaby Lake 630 integrated gpu on Linux.

## Issue

After inspection with renderdoc, it appears as if the texture is not properly being copied into the input texture before the compute shader runs, as the texture is all black. The working example, the texture appears the "Depth Pass" before the dispatch.

If I convert the shader to just write pure white, the output always works correctly.

## Relevant Code

Uploading textures and calling compute routines: https://github.com/BVE-Reborn/bve-reborn/blob/runtime/bve-render/src/texture.rs#L33-L70  
Compute pass doing transparency: https://github.com/BVE-Reborn/bve-reborn/blob/runtime/bve-render/src/compute.rs#L145-L178  
Compute shader: https://github.com/BVE-Reborn/bve-reborn/blob/runtime/bve-render/shaders/transparency.cs.glsl (spirv in same folder)  

## Building My Code

Clone (6789982 is the current commit at time of writing):
```
git clone https://github.com/BVE-Reborn/bve-reborn.git --branch wgpu-issue-253
```

Once cloned, building the code to run should be simple.

Build normally:
```
cargo build -p bve-client
```

Build with automatic renderdoc captures (won't work outside of renderdoc):
```
cd bve-client
cargo build --bin bve-client --features renderdoc
```

If you want to rebuild the shaders for any reason (requires glslc in path): 
```
cargo run bve-build -- --shaderc
```

## Sample Inputs

Here are two zip files with the inputs needed, one works, one doesn't. Unzip them, then when running the program, provide the path to the specified file as input.

(excuse the google drive link, it was too large for github)
[Failing.zip](https://github.com/gfx-rs/wgpu-rs/files/4465296/Failing.zip) - File `BodyA.b3d`
[Working.zip](https://drive.google.com/open?id=1HHpug2heMWCqL9-vYXbqXnBpRgNc9BWT) - File `InteriorAsectionA.csv`

## Running

Running should be simple, either run with `cargo run` or by manually calling the executable. All data besides the input is packed in the executable, so working directory doesn't matter.

`RUST_LOG=info,bve::runtime=trace,bve_render=trace ./bve-client /path/to/input/file`

Once running, a empty grey world will open up. The resources will load asynchronously and takes about 20-30 seconds in debug mode. If the RUST_LOG environment variable is set as shown, it will log when loading starts, texture packing starts and when it is finished and the result is uploaded to the gpu.

Once uploaded, you should see the model appear to the right. You can move around with wasdqz, unlock the mouse with left alt, and adjust MSAA with `,.`.

## Renderdoc

If built with renderdoc integration, it will automatically capture every time a texture is uploaded. This is the frame that the compute pass runs in. The first capture will be the default, pure white 1x1 texture, the second capture is the one where the texture atlas is uploaded.

## Postscript

I hope these are clear as to how to reproduce the issue. Feel free to ask any questions about building or reproducing either here or on matrix, I'll be glad to help :)

**Comment by kvark** [comment]
Unable to build the case using your instructions:
> error[E0599]: no method named `get_chunk` found for reference `&std::sync::Arc<runtime::Runtime<C>>` in the current scope
   --> bve/src/runtime/mod.rs:114:26
    |
114 |         let chunk = self.get_chunk(location.chunk).await;
    |                          ^^^^^^^^^ method not found in `&std::sync::Arc<runtime::Runtime<C>>`

**Comment by cwfitzgerald** [comment]
Ack, I think you caught me in the middle of a refactor, try the branch `wgpu-issue-253` which should be the affected commit.

**Comment by kvark** [comment]
Running it on the "good" data seems to panic for me:
>cargo run --bin bve-client -- input/Interior/
>     Running `target/debug/bve-client input/Interior/`
thread 'async-std/executor' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', /Users/dmalyshau/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.5.0/src/lib.rs:940:9

**Comment by cwfitzgerald** [comment]
You should run it on the `InteriorAsectionA.csv` file (not the folder).

**Comment by kvark** [comment]
This could be a caused by a silly bug we fixed in https://github.com/gfx-rs/wgpu/pull/573 . The patch wasn't release (I think we'll need to do it soonish), but the latest wgpu-rs points to the git master of `wgpu`, so you could test this easily if you just try using the latest wgpu-rs. Could you try that?

**Comment by kvark** [comment]
Actually, I grabbed all backwards-compatible changes from master, backported them on 0.5, and released a patch version just now. You can just do `cargo update -p wgpu-core` and try again. Hopefully, everything works now 🤞

**Comment by cwfitzgerald** [comment]
Unfortunately that doesn't appear to fix anything, the input is still black in renderdoc on the affected hardware.

**Comment by cwfitzgerald** [comment]
Renderdoc capture + binary with debug symbols so hopefully you can resolve callstacks.

https://send.firefox.com/download/fe7367ece4c4d38e/#LiNkwmmobwkWKshC-SSLeQ

**Comment by kvark** [comment]
I'm able to load the capture on Linux/NV. However, it's all red in internal assertion of RenderDoc in "vk_manager.cpp" basically saying that the layout transitions are broken. I'm going to try running it on Linux myself and see.

**Comment by kvark** [comment]
You'll need to align the bytesPerRow in the copies to 256 byte boundary, but that's not the reason you are getting problems.
I see that the barrier is missing, will be looking more into why.

**Comment by cwfitzgerald** [comment]
I thought bytes_per_row was for 3d textures only.

**Comment by kvark** [comment]
It's the rows_per_image for 3D copies. The bytes_per_row is everywhere :)

**Comment by kvark** [comment]
Here are the barriers I see:

First, just before the `copy_buffer_to_image`:
```
sType               VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER
pNext               NULL                                  
srcAccessMask       VK_ACCESS_TRANSFER_WRITE_BIT          
dstAccessMask       VK_ACCESS_TRANSFER_WRITE_BIT          
oldLayout           VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL  
newLayout           VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL  
srcQueueFamilyIndex -1                                    
dstQueueFamilyIndex -1                                    
image               ResourceId::269884
```

Strangeness: barrier is redundant!

Then after the copy:
```
sType               VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER
pNext               NULL                                  
srcAccessMask       VK_ACCESS_TRANSFER_WRITE_BIT          
dstAccessMask       VK_ACCESS_SHADER_WRITE_BIT            
oldLayout           VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL  
newLayout           VK_IMAGE_LAYOUT_GENERAL               
srcQueueFamilyIndex -1                                    
dstQueueFamilyIndex -1                                    
image               ResourceId::269884
```

Strangeness: the target access is `VK_ACCESS_SHADER_WRITE_BIT`. Wouldn't you want to read from it instead? I see that the `read_only` binding flag is true for it, so it's wgpu-core's fault. Fixing...

I also see that the binding is RW for the input texture:
> 0 0: inTexture Texture 2D RW Image ResourceId::269884 16401x1008 R8G8B8A8_UINT

Is this desired? Looks like the shader needs a `readonly` qualifier for this texture.

**Comment by kvark** [comment]
@cwfitzgerald I filed https://github.com/gfx-rs/wgpu/issues/597 to properly solve that (and will be working on it), and in the meantime I believe https://github.com/gfx-rs/wgpu/pull/598 is a short-term solution. Would you be able to check if it fixes the problem for you? I'd be happy to release a patch with this fix.

**Comment by cwfitzgerald** [comment]
> It's the rows_per_image for 3D copies. The bytes_per_row is everywhere :)

Aha!

> You'll need to align the bytesPerRow in the copies to 256 byte boundary

So I should pad out my image so that width * pixel_size is a multiple of 256? Would I still create the texture with the same size?

> Strangeness: barrier is redundant!

Is it because nothing has yet been written to the image yet?

> Is this desired? Looks like the shader needs a readonly qualifier for this texture.

I think this is one of those times where in desperately trying to debug stuff I removed some stuff but never put them back.

> Would you be able to check if it fixes the problem for you? 

Definitely, give me a bit.

**Comment by kvark** [comment]
> So I should pad out my image so that width * pixel_size is a multiple of 256? Would I still create the texture with the same size?

It's not about your image, it's about the data in the buffer specifically.

> Is it because nothing has yet been written to the image yet?

Upon further consideration, this is expected sometimes to issue barriers into the same state. The sync is needed as a pipeline barrier only, not changing any state of the resource, if we go from one mutable state to the same. So this one is OK.

**Comment by kvark** [comment]
Another interesting thing here, the pipeline barrier before the first copy:
```
sType               VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER
pNext               NULL                                   
srcAccessMask       VkAccessFlagBits(0)                    
dstAccessMask       VkAccessFlagBits(0)                    
srcQueueFamilyIndex -1                                     
dstQueueFamilyIndex -1                                     
buffer              ResourceId::269886                     
offset              0                                      
size                UINT64_MAX
```
It's followed by
```
sType               VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER
pNext               NULL                                   
srcAccessMask       VkAccessFlagBits(0)                    
dstAccessMask       VK_ACCESS_TRANSFER_READ_BIT            
srcQueueFamilyIndex -1                                     
dstQueueFamilyIndex -1                                     
buffer              ResourceId::269886                     
offset              0                                      
size                UINT64_MAX
```
The final access mask is correct. But the source one needs to be `VK_ACCESS_HOST_WRITE_BIT`.

**Comment by cwfitzgerald** [comment]
So I just decreased the size to 8k squared max, and it works perfectly fine. I'm just going to chalk this up to a driver/hardware bug and call it a day.
